spring.application.name=ProductService

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_product
spring.datasource.username=root
spring.datasource.password=tiger
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port= 8082

spring.servlet.multipart.enabled=true

cloudinary.cloud-name=ik5paz68
cloudinary.api-key=732793137571853
cloudinary.api-secret=phtuo8XXF3FeK-rtM_w20TGHdqI


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gowreshnaik1427@gmail.com
spring.mail.password=sbzh ndwt ubdr xmsy

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true